# version: '3.8'

# services:
#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: cargo_db
#       POSTGRES_USER: programmer
#       POSTGRES_PASSWORD: astana@1
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/

#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

# volumes:
#   postgres_data:


version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cargo_db
      POSTGRES_USER: programmer
      POSTGRES_PASSWORD: astana@1
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py import_locations && python manage.py create_cars && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:

